import Navbar from "@/components/Navbar/Navbar";
import "../styles/globals.scss";
import { Inria_Serif } from "next/font/google";
import Background from "../public/home-page/Home_Page_1920_dark.jpg";
import Image from "next/image";

const inria = Inria_Serif({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inria.className}>
        <Image
          alt="homepage background"
          src={Background}
          className="background"
          placeholder="blur"
          fill
          priority
          sizes="100vw"
          style={{ objectFit: "cover" }}
        />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
