import Navbar from "@/components/Navbar/Navbar";
import "../styles/globals.scss";
import { Inria_Serif } from "next/font/google";

const inria = Inria_Serif({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inria.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
